[package]
name = "faggot"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.8.21"
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["fs"] }
comrak = "0.11"
orgize = "0.9.0"
clap = { version = "4", features = ["derive"] }
 
