* Fast Accessable Goated Golang-less Opinionated Template-driven Blog system.
-----

F.A.G.G.O.T is yet another Markdown based static site generator. Yet this is *better* because it uses *Rust* and is *memory safe* .

[INSERT RANT ABOUT BLAZINGLY FAST RUST CRAP HERE].

Did I tell y'all it's memory safe guys? 

It uses the template.html in the template folder and the css file. 

Just put your posts in the posts folder and use the command cargo run. and it'll do everything for you and spit out the output in the folder named output (shocking right?). To view the site cd into the output folder and run a webserver there.You can start a web server by running ~python3 -m http.server 8000~. Or any other method you prefer.

Also as one wise girl said, "No there is no slur in the name you are mistaken. However, hypothetically if there was a slur, I would be allowed to use that one. Please refer to the project by its full name."

* Project Checklist
- [X] basic theming
- [X] home page with preview
- [X] code syntax highlighting
- [X] different themes and colorschemes
- [X] different template support
- [X] Config.toml for configuring the site
- [ ] embedded webserver for testing purposes
- [ ] Proper documenation
- [ ] Custom Markdown parser library
- [ ] A proper TUI interface 





TLDR, :3



And yes I wrote the readme in emacs org mode. Cry about it
